name: itc_observability_logger
description: Lightweight observability logger for Flutter mobile app developers in ITC Consortium.
version: 2.0.3
repository: https://github.com/Hackman-Adu/itc-observability-logger.git

environment:
  sdk: ^3.2.0

dependencies:
  http: ^1.2.1
  device_info_plus: ^10.1.0
  intl: ^0.19.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
